---
title: "__JT05: Federal Primary Jobs by Residence Area Characteristics Colorado 2019__ "
output:
  html_document:
    df_print: paged
  html_notebook: default
  pdf_document: default
  
---
```{r}



library(readr)
co_rac_SI03_JT05_2019 <- read_csv("co_rac_SI03_JT05_2019.csv")


```

__By Labor Information:__

```{r}
## (11 Digit number indicates census tract 2~state+3~county+6~tract=11 )


##Aggregated version of Total Number of Jobs in Colorado JT05 2019

TotalNumberofJobs<- co_rac_SI03_JT05_2019$C000
Geocode<-co_rac_SI03_JT05_2019$h_geocode
CreateDate<- co_rac_SI03_JT05_2019$createdate
TotalNumberofJobs29andYounger<-co_rac_SI03_JT05_2019$CA01
Numberofjobsforworkersage30to54<- co_rac_SI03_JT05_2019$CA02
Numberofjobsforworkersage55orolder<- co_rac_SI03_JT05_2019$CA03
Numberofjobswithearnings1250monthorless<- co_rac_SI03_JT05_2019$CE01
Numberofjobswithearnings1251monthto3333month <- co_rac_SI03_JT05_2019$CE02
Numberofjobswithearningsgreaterthan3333month <- co_rac_SI03_JT05_2019$CE03
NumberofjobsinNAICSsector11AgricultureForestryFishingandHunting<-co_rac_SI03_JT05_2019$CNS01
NumberofjobsinNAICSsector21MiningQuarryingandOilandGasExtraction<-co_rac_SI03_JT05_2019$CNS02
NumberofjobsinNAICSsector22Utilities<- co_rac_SI03_JT05_2019$CNS03





aggregate(x=cbind(TotalNumberofJobs,TotalNumberofJobs29andYounger, Numberofjobsforworkersage30to54, Numberofjobsforworkersage55orolder, Numberofjobswithearnings1250monthorless, Numberofjobswithearningsgreaterthan3333month, NumberofjobsinNAICSsector11AgricultureForestryFishingandHunting, NumberofjobsinNAICSsector22Utilities), by=list(CreateDate), FUN=sum)

NumberofjobsinNAICSsector23Construction<- co_rac_SI03_JT05_2019$CNS04
NumberofjobsinNAICSsector3133Manufacturing<- co_rac_SI03_JT05_2019$CNS05
NumberofjobsinNAICSsector42WholesaleTrade<- co_rac_SI03_JT05_2019$CNS06
NumberofjobsinNAICSsector4445RetailTrade<- co_rac_SI03_JT05_2019$CNS07
NumberofjobsinNAICSsector4849TransportationandWarehousing<- co_rac_SI03_JT05_2019$CNS08
NumberofjobsinNAICSsector51Information<- co_rac_SI03_JT05_2019$CNS09
NumberofjobsinNAICSsector52FinanceandInsurance <- co_rac_SI03_JT05_2019$CNS10
NumberofjobsinNAICSsector53RealEstateandRentalandLeasing<- co_rac_SI03_JT05_2019$CNS11



aggregate(x=cbind(NumberofjobsinNAICSsector23Construction, NumberofjobsinNAICSsector3133Manufacturing, NumberofjobsinNAICSsector42WholesaleTrade, NumberofjobsinNAICSsector4445RetailTrade, NumberofjobsinNAICSsector51Information, NumberofjobsinNAICSsector52FinanceandInsurance, NumberofjobsinNAICSsector53RealEstateandRentalandLeasing), by=list(co_rac_SI03_JT05_2019$createdate), FUN=sum)


NumberofjobsinNAICSsector53RealEstateandRentalandLeasing<- co_rac_SI03_JT05_2019$CNS11
NumberofjobsinNAICSsector54ProfessionalScientificandTechnicalServices<- co_rac_SI03_JT05_2019$CNS12
NumberofjobsinNAICSsector55ManagementofCompaniesandEnterprises<- co_rac_SI03_JT05_2019$CNS13
NumberofjobsinNAICSsector56AdministrativeandSupportandWasteManagementandRemediationServices<-co_rac_SI03_JT05_2019$CNS14
NumberofjobsinNAICSsector61EducationalServices<-co_rac_SI03_JT05_2019$CNS15
NumberofjobsinNAICSsector62HealthCareandSocialAssistance<- co_rac_SI03_JT05_2019$CNS16
NumberofjobsinNAICSsector71ArtsEntertainmentandRecreation<- co_rac_SI03_JT05_2019$CNS17



aggregate(x=cbind(NumberofjobsinNAICSsector53RealEstateandRentalandLeasing,NumberofjobsinNAICSsector54ProfessionalScientificandTechnicalServices, NumberofjobsinNAICSsector55ManagementofCompaniesandEnterprises,NumberofjobsinNAICSsector56AdministrativeandSupportandWasteManagementandRemediationServices,NumberofjobsinNAICSsector61EducationalServices,NumberofjobsinNAICSsector62HealthCareandSocialAssistance, NumberofjobsinNAICSsector71ArtsEntertainmentandRecreation), by=list(co_rac_SI03_JT05_2019$createdate), FUN=sum)



NAICSsector72FoodServices<- co_rac_SI03_JT05_2019$CNS18
NumberofjobsinNAICSsector81OtherServicesexceptPublicAdministration<- co_rac_SI03_JT05_2019$CNS19
NumberofjobsinNAICSsector92PublicAdministration<- co_rac_SI03_JT05_2019$CNS20

aggregate(x=cbind(NAICSsector72FoodServices,NumberofjobsinNAICSsector81OtherServicesexceptPublicAdministration, NumberofjobsinNAICSsector92PublicAdministration), by=list(co_rac_SI03_JT05_2019$createdate), FUN=sum)

```





__By Racial Demographics:__

```{r}
NumberofjobsforworkerswithRaceWhiteAlone<- co_rac_SI03_JT05_2019$CR01
NumberofjobsforworkerswithRaceBlackorAfricanAmericanAlone<- co_rac_SI03_JT05_2019$CR02
NumberofjobsforworkerswithRaceAmericanIndianorAlaskaNativeAlone<- co_rac_SI03_JT05_2019$CR03
NumberofjobsforworkerswithRaceAsianAlone<- co_rac_SI03_JT05_2019$CR05
NativeHawaiianorOtherPacificIslanderAlone <- co_rac_SI03_JT05_2019$CR05
NumberofjobsforworkerswithRaceTwoorMoreRaceGroups<- co_rac_SI03_JT05_2019$CR07
NumberofjobsforworkerswithEthnicityNotHispanicorLatino<- co_rac_SI03_JT05_2019$CT01
NumberofjobsforworkerswithEthnicityHispanicorLatino<-co_rac_SI03_JT05_2019 $CT02



aggregate(x=cbind(NumberofjobsforworkerswithRaceWhiteAlone, NumberofjobsforworkerswithRaceBlackorAfricanAmericanAlone, NumberofjobsforworkerswithRaceAmericanIndianorAlaskaNativeAlone,NumberofjobsforworkerswithRaceAsianAlone,  NativeHawaiianorOtherPacificIslanderAlone, NumberofjobsforworkerswithRaceTwoorMoreRaceGroups, NumberofjobsforworkerswithEthnicityNotHispanicorLatino, NumberofjobsforworkerswithEthnicityHispanicorLatino ), by=list(co_rac_SI03_JT05_2019$createdate), FUN=sum)



```



__By Educational Attainment:__

```{r}
NumberofjobsforworkerswithEducationalAttainmentLessthanhighschool<- co_rac_SI03_JT05_2019$CD01
EducationalAttainmentHighschoolorequivalentnocollege<- co_rac_SI03_JT05_2019$CD02 
EducationalAttainmentSomecollegeorAssociatedegree<- co_rac_SI03_JT05_2019$CD03
EducationalAttainmentBachelordegreeoradvanceddegree<- co_rac_SI03_JT05_2019$CD04
NumberofjobsforworkerswithSexMale<- co_rac_SI03_JT05_2019$CS01
NumberofjobsforworkerswithSexFemale<- co_rac_SI03_JT05_2019$CS02



aggregate(x=cbind(NumberofjobsforworkerswithEducationalAttainmentLessthanhighschool,EducationalAttainmentHighschoolorequivalentnocollege, EducationalAttainmentSomecollegeorAssociatedegree, EducationalAttainmentBachelordegreeoradvanceddegree, NumberofjobsforworkerswithSexMale,NumberofjobsforworkerswithSexFemale  ), by=list(co_rac_SI03_JT05_2019$createdate), FUN=sum)
```

```{r}

##My code when listing by geocode is very confusing and long, also not aggregated. 
aggregate(x=cbind(TotalNumberofJobs,TotalNumberofJobs29andYounger, Numberofjobsforworkersage30to54, Numberofjobsforworkersage55orolder, Numberofjobswithearnings1250monthorless, Numberofjobswithearningsgreaterthan3333month, NumberofjobsinNAICSsector11AgricultureForestryFishingandHunting, NumberofjobsinNAICSsector22Utilities), by=list(co_rac_SI03_JT05_2019$h_geocode), FUN=sum)
```





